## Book Recommendations

The below codes build a recommendation system to recommend book based on a book a given book. The data can be downloaded at [this link.](https://bryantstats.github.io/math460/python/books_rating.csv)

In [1]:
import pandas as pd
df = pd.read_csv('books_rating.csv', index_col=0)

In [2]:
df

,254,2276,2766,2977,3363,4017,4385,6242,6251,6323,...,271448,271705,273979,274061,274308,274808,275970,277427,277639,278418
bookTitle,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,7.0,0.0,0.0,...,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
from sklearn.neighbors import NearestNeighbors

model_knn = NearestNeighbors()
model_knn.fit(df)

book_title = 'You Belong To Me'
number_of_recommendation = 10

distances, indices = model_knn.kneighbors(df.loc[book_title, :].values.reshape(1, -1),
n_neighbors=number_of_recommendation)

print('Recommendations for', book_title)
for i in range(1, number_of_recommendation):
    print('{0}: {1}, with distance of {2}:'.format(i, df.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for You Belong To Me
1: Exclusive, with distance of 21.307275752662516:
2: Loves Music, Loves to Dance, with distance of 21.817424229271428:
3: The Cradle Will Fall, with distance of 23.45207879911715:
4: While My Pretty One Sleeps, with distance of 23.979157616563597:
5: The House of the Spirits, with distance of 24.166091947189145:
6: Before I Say Good-Bye, with distance of 25.0:
7: Weep No More My Lady, with distance of 25.592967784139454:
8: No Safe Place, with distance of 25.632011235952593:
9: Pleading Guilty, with distance of 25.67099530598687:

C:\Users\snguyen4\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

## Practice

Build a movie recommendation system using [this dataset](https://raw.githubusercontent.com/bryantstats/math460/master/python/movies_rating.csv?token=AKMTDDIKF5DJJQWQJD5GJKLBTXJM2) (Right click -> Save Link as -> change the extension from txt to csv).   Show the recommendations for some of your favourite movies. 

You can find more movies rating data at this link: https://grouplens.org/datasets/movielens/latest/