In [1]:
import numpy as np
import pandas as pd
def adaboost_steps(df, L=1):
    df['Stump 1']=np.sign(x2-2.5).astype(int)
    df['Weight 1'] = np.repeat(1/len(df), len(df))
    e1 = df[df['Stump 1']*df['y']==-1]['Weight 1'].sum()

    alpha1 = L*.5*np.log((1-e1)/e1)
    alpha1
    df['Weight 2'] = df['Weight 1']*np.exp(alpha1*(-df['y']*df['Stump 1']))
    df['Weight 2'] = df['Weight 2']/sum(df['Weight 2'])
    df

    df['Stump 2']=-np.sign(x1-1.5).astype(int)
    
    e2 = df[df['Stump 2']*df['y']==-1]['Weight 2'].sum()

    alpha2 = L*.5*np.log((1-e2)/e2)
    df['Weight 3'] = df['Weight 2']*np.exp(alpha2*(-df['y']*df['Stump 2']))
    df['Weight 3'] = df['Weight 3']/sum(df['Weight 3'])

    df['Stump 3']=-np.sign(x1-4.5).astype(int)
    e3 = df[df['Stump 3']*df['y']==-1]['Weight 3'].sum()

    alpha3 = L*.5*np.log((1-e3)/e3)

    return df

# Problem 4

In [6]:
#Toy Dataset
x1 = np.array([1, 1, 2, 2, 3, 3, 3, 4, 5, 5])
x2 = np.array([1, 3, 2, 4, 1, 2, 5, 4,   2, 5])
y = np.array([ 1, 1,-1, 1,-1, -1, 1, 1,  -1,-1])
X = np.vstack((x1,x2)).T
df = pd.DataFrame({'x1':x1, 'x2':x2, 'y':y})

adaboost_steps(df, L=1)

   x1  x2  y  Stump 1  Weight 1  Weight 2  Stump 2  Weight 3  Stump 3
0   1   1  1       -1       0.1    0.2500        1  0.153846        1
1   1   3  1        1       0.1    0.0625        1  0.038462        1
2   2   2 -1       -1       0.1    0.0625       -1  0.038462        1
3   2   4  1        1       0.1    0.0625       -1  0.166667        1
4   3   1 -1       -1       0.1    0.0625       -1  0.038462        1
5   3   2 -1       -1       0.1    0.0625       -1  0.038462        1
6   3   5  1        1       0.1    0.0625       -1  0.166667        1
7   4   4  1        1       0.1    0.0625       -1  0.166667        1
8   5   2 -1       -1       0.1    0.0625       -1  0.038462       -1
9   5   5 -1        1       0.1    0.2500       -1  0.153846       -1

In [7]:
adaboost_steps(df, L=.01)

   x1  x2  y  Stump 1  Weight 1  Weight 2  Stump 2  Weight 3  Stump 3
0   1   1  1       -1       0.1  0.101114        1  0.100856        1
1   1   3  1        1       0.1  0.099722        1  0.099467        1
2   2   2 -1       -1       0.1  0.099722       -1  0.099467        1
3   2   4  1        1       0.1  0.099722       -1  0.100318        1
4   3   1 -1       -1       0.1  0.099722       -1  0.099467        1
5   3   2 -1       -1       0.1  0.099722       -1  0.099467        1
6   3   5  1        1       0.1  0.099722       -1  0.100318        1
7   4   4  1        1       0.1  0.099722       -1  0.100318        1
8   5   2 -1       -1       0.1  0.099722       -1  0.099467       -1
9   5   5 -1        1       0.1  0.101114       -1  0.100856       -1

In [3]:
#Toy Dataset
x1 = np.array([1, 1, 2, 2, 3, 3])
x2 = np.array([2, 1, 4, 5, 1, 2])
y = np.array([ 1, 1,-1, -1,1, -1])
X = np.vstack((x1,x2)).T
df = pd.DataFrame({'x1':x1, 'x2':x2, 'y':y})

adaboost_steps(df, L=1)

   x1  x2  y  Stump 1  Weight 1  Weight 2  Stump 2  Weight 3  Stump 3
0   1   2  1       -1  0.166667       0.1        1  0.055556        1
1   1   1  1       -1  0.166667       0.1        1  0.055556        1
2   2   4 -1        1  0.166667       0.1       -1  0.055556        1
3   2   5 -1        1  0.166667       0.1       -1  0.055556        1
4   3   1  1       -1  0.166667       0.1       -1  0.500000        1
5   3   2 -1       -1  0.166667       0.5       -1  0.277778        1